#!/usr/bin/env bash
# Borrowed from: https://github.com/isledecomp/isle-portable/blob/master/packaging/linux/appimage/Build
set -e

export LD_LIBRARY_PATH="build/source/lib:$LD_LIBRARY_PATH"

# Sets a directory that has to have a following structure:
# build
# ├── bin
# │   ├── polanie
# │   └── polanie-editor2
# └── lib
#     ├── libSDL3.so -> libSDL3.so.0        		# Not important if available on the system
#     ├── libSDL3.so.0 -> libSDL3.so.0.3.0  		# Not important if available on the system
#     ├── libSDL3.so.0.3.0                  		# Not important if available on the system
#     ├── libSDL3_mixer.so -> libSDL3_mixer.so.0        # Not important if available on the system
#     ├── libSDL3.so.0 -> libSDL3_mixer.so.0.3.0  	# Not important if available on the system
#     └── libSDL3_mixer.so.0.3.0                  	# Not important if available on the system
# Can also be defined using --build=path
BUILD_SOURCE=source

# Sets where AppRun for AppImage is, can also be defined using --apprun=path
APPRUN_SOURCE=AppRun

# Sets where desktop file for AppImage is, can also be defined using --desktop-file=path
DESKTOP_FILE_SOURCE=polanie.desktop

# You know the drill
ICON_SOURCE=../../icons/polanie.png

cd $(dirname $0)

clean(){
    echo "Deleting build directory"
    rm -rf build
}

download(){
    if [ ! -e "$1" ]; then
        curl -Lo "$1" "$2"
    fi
}

prepare(){
    mkdir -p build/tools
    mkdir -p build/assets

    download build/tools/appimagetool.AppImage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage
    chmod u+x build/tools/appimagetool.AppImage

    download build/tools/linuxdeploy.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-$(uname -m).AppImage
    chmod u+x build/tools/linuxdeploy.AppImage

    if [ ! -f "build/assets/polaniecd.desktop" ]; then
        cp $DESKTOP_FILE_SOURCE build/assets/polanie.desktop
        cp $APPRUN_SOURCE build/assets/AppRun
        cp ../../icons/polanie.png build/assets/polanie.png
    fi

    if [ ! -d "build/source" ]; then
        cp -r $BUILD_SOURCE build/source
    fi
}

compile(){
    NO_STRIP=1 build/tools/linuxdeploy.AppImage \
        -e build/source/bin/polanie \
        -e build/source/bin/polanie-editor2 \
        -d build/assets/polanie.desktop \
        -i build/assets/polanie.png \
        --custom-apprun=AppRun \
        --appdir=build/AppDir
}

package(){
    build/tools/appimagetool.AppImage build/AppDir build/"Polanie_CD-$(uname -m).AppImage"
}

stop(){ # Can be used to do `Build clean stop` to just clean the directory
    exit
}

for arg in "$@"; do
    case "$arg" in
        --build=*)          BUILD_SOURCE="${arg#--build=}";;
        --apprun=*)         APPRUN_SOURCE="${arg#--apprun=}";;
        --desktop-file=*)   DESKTOP_FILE_SOURCE="${arg#--desktop-file=}";;
        --icon=*)           ICON_SOURCE="${arg#--icon=}";;
        *)                  "$arg"
    esac
done

prepare
compile
package
# Symlinks named as binaries in appimage can call these binaries specifically
# ln -s "Polanie_CD-$(uname -m).AppImage" polanie-editor2 
# ln -s "Polanie_CD-$(uname -m).AppImage" polanie
